---
- name: Pull Docker Image of Calculator
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Ensure Docker is running
      shell: |
        if ! pgrep -x "Docker"; then
          open --background -a Docker && echo "Waiting for Docker to start..." && while ! docker system info > /dev/null 2>&1; do sleep 1; done;
        fi

    - name: Pull image
      docker_image:
        name: shreyangupta03/calculator:latest
        source: pull

    - name: Stop and remove existing container if it exists
      shell: |
        if [ $(docker ps -a -q -f name=Calculator) ]; then
          docker stop Calculator
          docker rm Calculator
        fi

    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name Calculator shreyangupta03/calculator