---
- name: Pull Docker Image of Calculator
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: neogenkai/calculator:latest
        source: pull
#    - name: Start docker service
#      service:
#        name: docker
#        state: started
    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name Calculator neogenkai/calculator